# Nom à donner (obligatoire)
name: client-tests-workflow

# Evénement à préciser (obligatoire)
on:
  pull_request

jobs:
  # Job qui s'appelle 'test-client'
  test-client:
    # Ici on définit le système d'exploitation liste des se compatibles : https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    runs-on: ubuntu-latest
    steps:
      # Sert à récupérer le code du repo sur lequel le workflow est lancé d'où ce titre,
      # on spécifie le nom de l'action avec le mot clef uses, + sur uses : https://github.com/marketplace/actions/checkout
      - name: Check out code
        uses: actions/checkout@v2
        # On définit les commandes à lancer, d'où ce titre
      - name: Goto client and run tests
        run: cd client && npm i && npm test